GOOMER_DEVELOPMENT = True
GOOMER_STAGING = True
GOOMER_PRODUCTION = False




# Goomer Intergration Token

GOOMER_INTEGRATION_TOKEN_PROD = 'fkuzhdP0633tBM2nqWyToHxYiDPwhsKg'
GOOMER_INTEGRATION_TOKEN_STAGING = 'SxNLU3kxSko46DE75xAN2BoekJcMN9hK'

# Goomer Config urls

GOOMER_AUTH_URL_PROD = 'https://api-integration.goomer.app/auth/v1/authorize'
GOOMER_AUTH_URL_STAGING = 'https://api-integration.goomer.ninja/auth/v1/authorize'

GOOMER_REFRESH_TOKEN_URL_PROD = 'https://api-integration.goomer.app/auth/v1/refresh'
GOOMER_REFRESH_TOKEN_URL_STAGING = 'https://api-integration.goomer.ninja/auth/v1/refresh'

GOOMER_ORDER_DETAILS_URL_PROD = 'https://api-integration.goomer.app/orders/v1/details/' 
GOOMER_ORDER_DETAILS_URL_STAGING = 'https://api-integration.goomer.ninja/orders/v1/details/'

GOOMER_ORDER_CALLBACK_URL_PROD = 'https://api-integration.goomer.app/orders/v1/accept/'
GOOMER_ORDER_CALLBACK_URL_STAGING = 'https://api-integration.goomer.ninja/orders/v1/accept/'

GOOMER_WEBHOOK_REGISTER_URL_PROD = 'https://api-integration.goomer.app/webhook/v1/setup'
GOOMER_WEBHOOK_REGISTER_URL_STAGING = 'https://api-integration.goomer.ninja/webhook/v1/setup'







if GOOMER_PRODUCTION:
    GOOMER_AUTH_URL = GOOMER_AUTH_URL_PROD
    GOOMER_REFRESH_TOKEN_URL = GOOMER_REFRESH_TOKEN_URL_PROD
    GOOMER_ORDER_DETAILS_URL = GOOMER_ORDER_DETAILS_URL_PROD
    GOOMER_ORDER_CALLBACK_URL = GOOMER_ORDER_CALLBACK_URL_PROD
    GOOMER_WEBHOOK_REGISTER_URL = GOOMER_WEBHOOK_REGISTER_URL_PROD
    GOOMER_INTEGRATION_TOKEN = GOOMER_INTEGRATION_TOKEN_PROD



elif GOOMER_STAGING:
    GOOMER_AUTH_URL = GOOMER_AUTH_URL_STAGING
    GOOMER_REFRESH_TOKEN_URL = GOOMER_REFRESH_TOKEN_URL_STAGING
    GOOMER_ORDER_DETAILS_URL = GOOMER_ORDER_DETAILS_URL_STAGING
    GOOMER_ORDER_CALLBACK_URL = GOOMER_ORDER_CALLBACK_URL_STAGING
    GOOMER_WEBHOOK_REGISTER_URL = GOOMER_WEBHOOK_REGISTER_URL_STAGING
    GOOMER_INTEGRATION_TOKEN = GOOMER_INTEGRATION_TOKEN_STAGING




    
else:
    
    # default is staging for goomer
    GOOMER_AUTH_URL = GOOMER_AUTH_URL_STAGING
    GOOMER_REFRESH_TOKEN_URL = GOOMER_REFRESH_TOKEN_URL_STAGING
    GOOMER_ORDER_DETAILS_URL = GOOMER_ORDER_DETAILS_URL_STAGING
    GOOMER_ORDER_CALLBACK_URL = GOOMER_ORDER_CALLBACK_URL_STAGING
    GOOMER_WEBHOOK_REGISTER_URL = GOOMER_WEBHOOK_REGISTER_URL_STAGING
    GOOMER_INTEGRATION_TOKEN = GOOMER_INTEGRATION_TOKEN_STAGING


    